<?php

declare(strict_types=1);

namespace Empaphy\Colorphul;

use Empaphy\Colorphul\Terminal\TerminalEmulatorColorScheme;

/**
 * A theme that can be generated by providing a {@see \Empaphy\Colorphul\ColorSchemeInterface}
 */
interface ThemeGeneratorInterface
{
    public function generate(string $name, TerminalEmulatorColorScheme $scheme, string $filePath): void;
}
